### ISSUE TITLE
Getting different Etag on each new execution of localstack

### ISSUE THREAD

**Issue by gtwuser** [elgohr/go-localstack#281]
Getting different ETag on each new execution of localstack, if this is not an issue kindly share suggestions so as to how to get same ETag for a specific S3 object `GET` operation. 

Requirement: While running unit tests, the expected(HARD-CODED) ETag doesn't match ETag received during GET operation.
Code Snippet
```bash
                        getObject := s3.GetObjectInput{
				Bucket: aws.String(tt.DataBucket),
				Key:    aws.String(tt.ManifestFilePath),
			}

			res, err := tt.s3Client.GetObjectWithContext(context.Background(), &getObject)
			if err != nil {
				fmt.Println(err.Error())
				if err.Error() != tt.want {
					t.Errorf("Want %s Got %s", tt.want, err.Error())
				}
			}
			eTag := res.ETag // this is always changing on every execution, my requirement is to get same or 
                                                                   constant ETag value.

**Comment by elgohr** [comment]
Hey, sorry for the late response. Please head over to https://github.com/localstack/localstack/issues , as this repository is not containing the implementation of localstack.
You should also make sure that your file is not changing between runs https://teppen.io/2018/06/23/aws_s3_etags/
