### ISSUE TITLE
Any chance to use aws-sdk-go-v2 instead?

### ISSUE THREAD

**Issue by YikSanChan** [elgohr/go-localstack#384]
Since this is such a new project, I recommend using the latest version of Go SDK

**Comment by elgohr** [comment]
Sure
```
cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion("us-east-1"),
		config.WithEndpointResolver(aws.EndpointResolverFunc(
			func(service, region string) (aws.Endpoint, error) {
				return aws.Endpoint{URL: l.Endpoint(localstack.SQS)}, nil
			})),
		config.WithCredentialsProvider(credentials.StaticCredentialsProvider{
			Value: aws.Credentials{
				AccessKeyID: "dummy", SecretAccessKey: "dummy", SessionToken: "dummy",
				Source: "Hard-coded credentials; values are irrelevant for local DynamoDB",
			},
		}),
	)
```
Will document this later, as I remember that you have to set some additional parameter for s3 clients (otherwise they prefix the URL with the bucket).

**Comment by elgohr** [comment]
Or do you mean inside the project?

**Comment by YikSanChan** [comment]
@elgohr My bad I didn't explain it clearly.

> Or do you mean inside the project?

Yes, I mean inside the project

**Comment by elgohr** [comment]
Done in https://github.com/elgohr/go-localstack/commit/a95fe1f723be0d9a90780a67c6fc4c9165b8f693 and https://github.com/elgohr/go-localstack/commit/b4fe1a84066f53616f43ddf12f3b7ead574393bb . Still keeping v1 as a dependency for examples https://github.com/elgohr/go-localstack/blob/main/example_test.go
