### ISSUE TITLE
Question: How to start on a fixed port like 4566

### ISSUE THREAD

**Issue by gtmtech** [elgohr/go-localstack#461]
Hi, by default it seems to start on an ephemeral port. 

Is it possible to start it on port 4566 instead?

Thanks

**Comment by gtmtech** [comment]
Will you take a PR? I'm getting it working on my local fork

**Comment by elgohr** [comment]
Sure

**Comment by elgohr** [comment]
Just out of curiosity: Why do you need that? :)
