### ISSUE TITLE
isRunning fails when docker host responds with fully qualified image names 

### ISSUE THREAD

**Issue by jgresty** [elgohr/go-localstack#905]
On some OCI hosts (eg podman), the get container call responds with a fully qualified name: eg `docker.io/library/go-localstack:latest`. This fails the equality check in `isRunning` which is expecting an unqualified name (eg `go-localstack`). As a result calls to `Start*` fail.

An easy fix would be:
```diff
-		if c.Image == imageName {
+		if strings.Contains(c.Image, imageName) {
```
however that may have false positives.

**Comment by elgohr** [comment]
Would be great to reproduce this within a test-run.
I guess you're running a self-hosted runner that has podman installed?

**Comment by jgresty** [comment]
Steps to reproduce it:
 - install podman, enable podman.socket (`systemctl start --user podman.socket`)
 - set `DOCKER_HOST` to the above socket (eg `DOCKER_HOST=unix:///run/user/1000/podman/podman.sock`)
 - Try to start a localstack instance locally:
 ```go
    opt, _ := localstack.WithClientFromEnv()
    l, _ := localstack.NewInstance(opt)
    if err := l.StartWithContext(ctx); err != nil {
        log.Fatalf("Could not start localstack %v", err)
    }
 ```
 
To capture this in a test case, it would either need to run with a podman host or the moby client would have to be mocked. Not sure if you want to complicate the current test setup by that extent just for this edge case.

**Comment by elgohr** [comment]
I guess we would need https://github.com/actions/runner/issues/505 for this

**Comment by elgohr** [comment]
🤔 looks like podman is preinstalled already 
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools
